name: Go Backend CI/CD

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'  # Use the latest Go version

      - name: Install Dependencies
        run: go mod tidy

      - name: Build Go Backend
        run: go build -v ./...

      - name: Run Tests
        run: go test ./...
